spring:
  application:
    name: item-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
    registry-fetch-interval-seconds: 30

  instance:
    lease-renewal-interval-in-seconds: 30

---
server:
  port: 8001

spring:
  profiles: itemservice01

---
server:
  port: 8002

spring:
  profiles: itemservice02
